name: FlutterCI # CI名称
on:   [push] # 触发条件是push操作

# 这个工作流程需要执行的任务
jobs:
  process:
    name: Update flutter framework
    # 运行在哪个平台（这里是MacOS）
    runs-on: macos-latest
    # 这个任务的步骤
    steps:
      # 拉取项目代码（这是一个官方提供的action，如需要使用项目仓库中代码用来构建、测试等的，使用checkout action可以自动拉取项目仓库的代码。）
      - uses: actions/checkout@v2
      
      - name: Install git-lfs 处理大文件
        run: brew install git-lfs && git lfs install #进入本地仓库目录初始化 LFS

      - name: 跟踪特定文件夹
        run: git lfs track MixedDeviOSProject/mixed_dev_flutter_app/ && git add .gitattributes #进入本地仓库目录初始化 LFS

      # 建立 Flutter 环境
      - name: Flutter action
        uses: subosito/flutter-action@v2 # 第三方flutter的Action，它可以在服务器配置一个Flutter环境
        with: # 这里的version和channel要跟Flutter工程师电脑上的Flutter环境保持一致（通过flutter doctor指令可以查看具体信息  ）
          channel: "stable"
          flutter-version: "2.5.1"
            
      

      # 想让我们CI做的事情！
      # - run: cd MixedDeviOSProject && touch sss.text #这个是可以提交成功的！！！
      - run: cd mixed_dev_flutter_project && flutter build ios-framework --output=../MixedDeviOSProject/mixed_dev_flutter_app
      
      


      - run: |
         git add .
         git commit -m "update flutter framework"
         
      

      - name: Push changes
        uses: ad-m/github-push-action@master
        # timeout-minutes: 45
        with: 
          github_token: ${{ secrets.FLUTTER_CI_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
